# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'
  
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      pip install pytest pytest-azurepipelines
      pytest
    displayName: 'pytest'

  - task: CmdLine@2
    inputs:
      script: 'touch file1.txt'

  - task: CmdLine@2
    inputs:
      script: 'echo file1.txt'
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here
        echo 'Hello world'
        cat > /bin/bash --noprofile --norc /home/vsts/work/_temp/file.txt << ENDOFFILE
        My File, My Choice
        I have the right to write what I want in this file
        and no NSA can stop me from doing it.
            I had privacy before NSA and the whole internet
        and now I'm just a tiny little book that was read
        by everyone....
        ENDOFFILE
        echo /file.txt

